name: "GCP Sandbox Access"
run-name: GCP Sandbox - ${{ inputs.TEAM }} - ${{ github.actor }} for ${{ inputs.PURPOSE }} for ${{ inputs.DURATION }}

on:
  workflow_dispatch:
    inputs:
      TEAM:
        description: "Select your team, [CSE = Cloud Solution Engineering], [MCS = Managed Cloud Solutions] "
        type: choice
        options:
          - CSE_DEVOPS
          - MCS_DEVOPS
          - CSE_DEV
          - SOLUTION_ARCHITECT
          - DATA_TEAM
        required: true
      DURATION:
        description: "Select the duration of access required in hours "
        type: choice
        required: true
        options:
          - 2 Hours
          - 4 Hours
          - 8 Hours
          - 16 Hours
          - 24 Hours
          - 48 Hours
          - 96 Hours
          - 120 Hours
          - 168 Hours
      OTHER_USERS:
        description: Enter emails spearated by comma of other users that require access to the sandbox. e.g email1,email2,email3 (Optional)
      PURPOSE:
        description: "Short description"
        type: string
        default: "POC"


defaults:
  run:
    shell: bash

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
