global:
  cloud_identity_domain: "cloudpoet.in"
  location: "asia-south1"
  billing_account_name: "CloudpoetMain"
  authorized_domains:
    - "cloudpoet.in"
    - "example.com"
  max_allowed_projects_per_user: 1

folder:
  master_display_name: "Sanbox Provisioner"
  # By default, the master folder will get created on organization level.
  # Set master_parent_id only if sandbox needs to be created inside another folder.
  # It should be of the format folders/123456789
  parent_id: "default"
  # Create as many folders as needed below for different teams
  team_folders:
    - "Team-DevOps"
    - "Team-Data"
    - "Team-3"
    - "Team-4"
