output "project_id" {
  description = "The ID of the created project"
  value       = module.project_factory.project_id
}

output "service_account_email" {
  description = "The email of the created provisioner service account"
  value       = google_service_account.service_account.email
}

output "cloud_run_service_url" {
  description = "The URL of the deployed Cloud Run service"
  value       = local.config.deploy_cloud_run ? module.cloud_run[0].service_url : "Bootstrap complete. Set deploy_cloud_run=true to deploy"
}

output "custom_domain_dns_records" {
  description = "The DNS records to configure for the custom domain"
  value       = local.config.deploy_cloud_run ? module.cloud_run[0].custom_domain_dns_records : "N/A"
}

output "firestore_database_id" {
  description = "The ID of the Firestore database"
  value       = google_firestore_database.database.name
}

output "auth_secret" {
  description = "The generated authentication secret (sensitive)"
  value       = random_id.auth_secret.b64_std
  sensitive   = true
}

output "next_steps" {
  description = "Next steps to complete the setup"
  value       = local.config.deploy_cloud_run ? "Cloud Run deployed. Setup complete!" : <<-EOT
    ========================================
    BOOTSTRAP COMPLETE - NEXT STEPS
    ========================================

    PROJECT: ${module.project_factory.project_id}

    STEP 1: Configure OAuth Consent Screen
    ----------------------------------------
    URL: https://console.cloud.google.com/auth/overview?project=${module.project_factory.project_id}&supportedpurview=project

    Instructions:
    - Select "Internal" user type
    - Fill in App name: "GCP Sandbox Provisioner"
    - Add your support email
    - Add authorized domain (if using custom domain)
    - Save and continue

    Screenshots: See docs/images/sandbox-oauth-1.png

    STEP 2: Create OAuth Client Credentials
    ----------------------------------------
    URL: https://console.cloud.google.com/auth/clients?project=${module.project_factory.project_id}&supportedpurview=project

    Instructions:
    - Click "CREATE CREDENTIALS" > "OAuth client ID"
    - Application type: "Web application"
    - Name: "Sandbox Provisioner Web Client"
    - Authorized redirect URIs:
      * http://localhost:3000/api/auth/callback/google (for local dev)
      * https://YOUR_DOMAIN/api/auth/callback/google (for production)
    - Click "CREATE"
    - Copy CLIENT_ID and CLIENT_SECRET

    Screenshots: See docs/images/sandbox-oauth-2.png through sandbox-oauth-5.png

    STEP 3: Get Google AI API Key
    ----------------------------------------
    URL: https://makersuite.google.com/app/apikey

    Instructions:
    - Create new API key or use existing
    - Copy the API key (you'll add it to Secret Manager next)

    STEP 4: Update Application Secret in Google Secret Manager
    ----------------------------------------
    A JSON secret has been created for you: sandbox-provisioner-system-secret

    Update it with your actual credentials:

    cat <<EOF | gcloud secrets versions add sandbox-provisioner-system-secret \
      --project=${module.project_factory.project_id} \
      --data-file=-
    {
      "GOOGLE_CLIENT_ID": "YOUR_CLIENT_ID.apps.googleusercontent.com",
      "GOOGLE_CLIENT_SECRET": "YOUR_CLIENT_SECRET",
      "AUTH_SECRET": "$(terraform output -raw auth_secret)",
      "GOOGLE_API_KEY": "YOUR_AI_API_KEY",
      "NEXTAUTH_URL": "http://localhost:3000"
    }
    EOF

    Note: AUTH_SECRET has been pre-generated by Terraform.
    Replace only YOUR_CLIENT_ID, YOUR_CLIENT_SECRET, and YOUR_AI_API_KEY.

    STEP 5: Update Terraform Configuration
    ----------------------------------------
    Update terraform.tfvars with NON-SECRET values only:

    deploy_cloud_run = true

    Note: Secrets are now stored in Secret Manager and will be
    automatically retrieved by Cloud Run at runtime.

    STEP 6: Deploy Cloud Run
    ----------------------------------------
    terraform apply --auto-approve

    Cloud Build will automatically build and deploy your container.

    ========================================
    Documentation: See docs/ directory for screenshots
    ========================================
  EOT
}
