name: GCP Sandbox provisioning

on:
  workflow_dispatch:
    inputs:
      USER_EMAIL:
        description: "Email of user"
        required: true
        type: string
      PERMISION_SET:
        description: "Access role for user"
        type: choice
        options:
          - ADMINISTRATOR
          - READ_ONLY
        required: true
      DURATION:
        description: "Select the duration of access required in hours "
        type: choice
        required: true
        options:
          - 1 Minutes
          - 1 Hours
          - 2 Hours
          - 4 Hours
          - 8 Hours
          - 16 Hours
          - 40 Hours
      PURPOSE:
        description: "Short description"
        type: string

jobs:
  provisioning_gcp_project:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      ACTIONS_STEP_DEBUG: true
    steps:
    - uses: 'actions/checkout@v1'
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        token_format: 'access_token'
        workload_identity_provider:  ${{ secrets.WIP_PROVIDER_ID }}
        service_account:  ${{ secrets.MASTER_SERVICE_ACCOUNT_EMAIL }}
        # project_id: ${{ secrets.SANDBOX_MASTER_PROJECT_ID }}
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: "test auth"
      run: gcloud auth list

    - name: "test sa"
      run: gcloud projects list

    - name: "test prj sa"
      run: echo '${{ steps.auth.outputs.access_token }}'


    # - name: Invoke function over HTTP
    #   uses: fjogeleit/http-request-action@v1
    #   with:
    #     url: 'https://asia-south1-sandbox-master-prjc.cloudfunctions.net/gcp-sandbox-manager'
    #     method: 'POST'
    #     customHeaders: '{"Content-Type":"application/json"}'
    #     bearerToken: '$(gcloud auth print-identity-token)'
    #     data: '{"request_duration":"${{ inputs.DURATION }}","event_type":"sandbox-provision"}'

    - name: "Call API"
      uses: indiesdev/curl@v1.1
      with:
        url: https://asia-south1-sandbox-master-prjc.cloudfunctions.net/gcp-sandbox-manager
        method: "POST"
        headers: '{"Content-Type":"application/json"}'
        body: '{"request_duration":"${{ inputs.DURATION }}","event_type":"sandbox-provision"}'
        bearer-token: '${{ steps.auth.outputs.access_token }}'

    # - name: "Invoke gcloud function"
    #   run: gcloud functions call gcp-sandbox-manager --data '{"request_duration":"${{ inputs.DURATION }}","event_type":"sandbox-provision"}' --region asia-south1 --project sandbox-master-prjc
      
    # - name: 'Alert on Slack about project creation status'
    #   uses: act10ns/slack@v1
    #   with:
    #     status: ${{ job.status }}
    #     config: .github/config/slack.yaml
    #   if: always()
