name: GCP Sandbox request

on:
  workflow_dispatch:
    inputs:
      USER_EMAIL:
        description: "Email of user"
        required: true
        type: string
        default: "vishal.kapse@cldcvr.com"
      PERMISION_SET:
        description: "Access role for user"
        type: choice
        options:
          - ADMINISTRATOR
          - READ_ONLY
        required: true
      DURATION:
        description: "Select the duration of access required in hours "
        type: choice
        required: true
        options:
          - 1 Hours
          - 2 Hours
          - 4 Hours
          - 8 Hours
          - 16 Hours
          - 40 Hours
      PURPOSE:
        description: "Short description"
        type: string
      SUPPORT_TICKET:
        description: "Paste the support ticket url here"
        type: string
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
